apiVersion: 1
datasources:
  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url: http://victorialogs.railway.internal:$VL_PORT
    isDefault: true
    basicAuth: true
    basicAuthUser: $VL_USERNAME
    secureJsonData:
      basicAuthPassword: $VL_PASSWORD
