apiVersion: 1
datasources:
  - name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url: http://0.0.0.0:$VL_PORT
    isDefault: true
    basicAuth: true
    basicAuthUser: $VL_USERNAME
    basicAuthPassword: $VL_PASSWORD
